---
title: "A5_Grenier_Braeden.rmd"
author: "Braeden Grenier"
date: "2023-02-07"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(tidyr)
library(data.table)
library(gridExtra)
library(lmtest)
library(MuMIn)
library(MASS)
```

#1. Project Folder
project folder is unable to sync with RStudio; unable to push or pull to fix it

https://github.com/BradyGrenier/BIOL432Assignment5

A new project Folder was made to help prevent future errors with this.

#2. Code for Each of the Following

##1. Importing Measurements
```{r}
test = read.csv("measurements.csv")

mdata = read.csv("measurements.csv")
```

##2. Making a New Abbreviated Column with GSUB
```{r}
mdata2 = mdata %>% 
  mutate(Sp = gsub("(^[[:alpha:]])[[:alpha:]]*","\\1.",mdata$OrganismList))
mdata2
```

##3. New Dataset with Sp Column
```{r}
Sp = mdata2$Sp
mdata2["OrganismList"] <- Sp
mdata3 = dplyr::select(mdata2, -c(Sp))
mdata3

write.csv(mdata3, file = "MeasShort.csv")
```

## testing
```{r}
write.csv(test, file = "NEWTEST")
```

